spring:
  application:
    name: dynamic-tp-nacos-cloud-practise
  profiles:
    active: dev
  config:
    import: nacos:dynamic-tp-nacos-cloud-demo-dtp-dev.yml
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: GZ # 集群名称
      config:
        server-addr: localhost:8848
        file-extension: yml
        extension-configs:
          - dataId: ${spring.application.name}-dtp-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            group: DEFAULT_GROUP
            refresh: true  # 必须配置，负责自动刷新不生效
        refresh-enabled: true
